name: ecommerce
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  shared_preferences: ^0.5.12+4
  fluttertoast: ^7.1.6
  image_picker: ^0.6.7+17
  firebase_storage: ^5.2.0
  flutter_staggered_grid_view: ^0.3.3
  provider: ^4.3.2+3
  path_provider: ^1.6.24
  image: ^2.1.19
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
fonts:
  - family: Signatra
    fonts:
      - asset: assets/fonts/Signatra.ttf

assets:
  - images/welcome.png
  - images/login.png
  - images/admin.png
  - images/cash.png
